version: "3.9"

services:
  app:
    build: simple_project_for_deploy
    # command: bash -c entrypoint.sh
    container_name: simple_project
    ports:
      - 80:8000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    container_name: simple_project_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=some_bd_name
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  redis_cache:
    image: redis
    container_name: redis_cache
    volumes:
      - redis_cache_data:/data

volumes:
  postgres_db_data:
  redis_cache_data:
